version: '3'

services:
  client:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./client:/app
    command: yarn serve

  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    ports:
      - 8888:8888
    volumes:
      - ./server:/api
